databases:
  - name: n8n-database
    plan: free
    databaseName: n8n
    user: n8n
    region: oregon

services:
  - name: n8n-servicio
    type: web
    plan: free
    region: oregon
    runtime: docker
    image:
      url: docker.io/n8nio/n8n:latest
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: psql
          name: n8n-database
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: psql
          name: n8n-database
          property: port
      - key: DB_POSTGRESDB_USER
        fromService:
          type: psql
          name: n8n-database
          property: user
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: psql
          name: n8n-database
          property: database
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: psql
          name: n8n-database
          property: password
      - key: DB_POSTGRESDB_SSL
        value: true
      - key: GENERIC_TIMEZONE
        value: America/Bogota
